-- AlterTable
ALTER TABLE "AlatAWL" ADD COLUMN     "latitude" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "longitide" DECIMAL(65,30) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "AlatAWS" ADD COLUMN     "latitude" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "longitide" DECIMAL(65,30) NOT NULL DEFAULT 0;
